insert INTO solar_energy.power_core_channel_b SELECT * FROM power_core_new_1 a
WHERE a.channel LIKE 'B%'

solar_energyCREATE TABLE power_core_channel_e AS (SELECT * FROM power_core_new_1 a WHERE a.channel LIKE 'E%')

SELECT COUNT(*) FROM power_core_channel_b


solar_energyCREATE TABLE REPORT1 AS (
SELECT SUBSTRING(CHANNEL, 1, 1)  AS CHANNEL1, AVG(T1),AVG(T2),AVG(T3),AVG(T4),AVG(T5),AVG(T6),AVG(T7),AVG(T8),AVG(T9),AVG(T10),AVG(T11),AVG(T12),AVG(T13),AVG(T14),AVG(T15),AVG(T16),AVG(T17),AVG(T18),AVG(T19),AVG(T20),AVG(T21),AVG(T22),AVG(T23),AVG(T24),AVG(T25),AVG(T26),AVG(T27),AVG(T28),AVG(T29),AVG(T30),AVG(T31),AVG(T32),AVG(T33),AVG(T34),AVG(T35),AVG(T36),AVG(T37),AVG(T38),AVG(T39),AVG(T40),AVG(T41),AVG(T42),AVG(T43),AVG(T44),AVG(T45),AVG(T46),AVG(T47),AVG(T48) 
FROM power_core_new_1
GROUP BY CHANNEL1
) 

CREATE TABLE REPORT2 AS 
(
SELECT channel1, 'T1' AS HOUR , `AVG(T1)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T2' AS HOUR , `AVG(T2)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T3' AS HOUR , `AVG(T3)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T4' AS HOUR , `AVG(T4)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T5' AS HOUR , `AVG(T5)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T6' AS HOUR , `AVG(T6)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T7' AS HOUR , `AVG(T7)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T8' AS HOUR , `AVG(T8)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T9' AS HOUR , `AVG(T9)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T10' AS HOUR , `AVG(T10)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T11' AS HOUR , `AVG(T11)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T12' AS HOUR , `AVG(T12)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T13' AS HOUR , `AVG(T13)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T14' AS HOUR , `AVG(T14)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T15' AS HOUR , `AVG(T15)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T16' AS HOUR , `AVG(T16)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T17' AS HOUR , `AVG(T17)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T18' AS HOUR , `AVG(T18)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T19' AS HOUR , `AVG(T19)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T20' AS HOUR , `AVG(T20)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T21' AS HOUR , `AVG(T21)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T22' AS HOUR , `AVG(T22)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T23' AS HOUR , `AVG(T23)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T24' AS HOUR , `AVG(T24)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T25' AS HOUR , `AVG(T25)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T26' AS HOUR , `AVG(T26)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T27' AS HOUR , `AVG(T27)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T28' AS HOUR , `AVG(T28)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T29' AS HOUR , `AVG(T29)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T30' AS HOUR , `AVG(T30)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T31' AS HOUR , `AVG(T31)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T32' AS HOUR , `AVG(T32)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T33' AS HOUR , `AVG(T33)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T34' AS HOUR , `AVG(T34)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T35' AS HOUR , `AVG(T35)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T36' AS HOUR , `AVG(T36)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T37' AS HOUR , `AVG(T37)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T38' AS HOUR , `AVG(T38)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T39' AS HOUR , `AVG(T39)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T40' AS HOUR , `AVG(T40)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T41' AS HOUR , `AVG(T41)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T42' AS HOUR , `AVG(T42)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T43' AS HOUR , `AVG(T43)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T44' AS HOUR , `AVG(T44)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T45' AS HOUR , `AVG(T45)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T46' AS HOUR , `AVG(T46)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T47' AS HOUR , `AVG(T47)` FROM REPORT1 
UNION ALL
SELECT channel1, 'T48' AS HOUR , `AVG(T48)` FROM report1 
)
solar_energyreport2



